version: '3.8'


services:
  db_node_ayd:
    image: postgres:14
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data