version: '3.8'

services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw