// Generated by https://quicktype.io

export interface FileResponse {
    fieldname:    string;
    originalname: string;
    encoding:     string;
    mimetype:     string;
    destination:  string;
    filename:     string;
    path:         string;
    size:         number;
}
